---
title: "What Makes a Hollywood Movie a Hit or a Flop?"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Celena Kim"
date: today

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
---


::: {.callout-tip icon="false"}
## Github Repo Link

<https://github.com/stat301-1-2023-fall/final-project-1-celenakim>
:::

## Introduction
As an avid movie lover, I have always been curious about what factors play into making some Hollywood movies critically acclaimed blockbusters while others fade into the background. Beyond solely the opening weekend numbers, I am interested in exploring the interplay between more extensive variables that contribute to a film’s propensity to ultimately be a hit or a flop. Specifically, I think it would be very interesting to focus on the five factors of critic and audience ratings, opening weekend revenue, gross (domestic, foreign, and worldwide), budget and budget recovery, and Oscar wins. By focusing on these main variables for my analysis, I hope to explore my research question by discovering patterns and compelling correlations between the variables on a range of univariate to multivariate levels. I am interested in exploring whether certain variables affect another and how certain variables work together to contribute to a movie’s overall success rate. In order to carry out this analysis, I will be utilizing a data set found on the Kaggle website called “Hollywood Hits and Flops (2007 - 2023)”, described in the next section.

## Data Overview and Quality
text

# Explorations: What variables contribute to a movie's overall success rate?
## Variable 1: Ratings

## Variable 2: Opening weekend revenue

## Variable 3: Domestic, foreign, & worldwide gross

## Variable 4: Budget recovery

## Variable 5: Oscar wins

## Conclusion
text

## References
text

## Appendix: technical info
text

## Appendix: extra explorations
text


