---
title: "Progress Memo 1"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Celena Kim"
date: today

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  warning: false

from: markdown+emoji 
---

::: {.callout-tip icon="false"}
## Github Repo Link

<https://github.com/stat301-1-2023-fall/final-project-1-celenakim>
:::

## Data source

```{r}
library(tidyverse)
data1 <- read.csv("data/The Hollywood Inider - all data - 2007.csv")
data2 <- read.csv("data/The Hollywood Inider - all data - 2008.csv")
data3 <- read.csv("data/The Hollywood Inider - all data - 2009.csv")
data4 <- read.csv("data/The Hollywood Inider - all data - 2010.csv")
data5 <- read.csv("data/The Hollywood Inider - all data - 2011.csv")
data6 <- read.csv("data/The Hollywood Inider - all data - 2012.csv")
data7 <- read.csv("data/The Hollywood Inider - all data - 2013.csv")
data8 <- read.csv("data/The Hollywood Inider - all data - 2014.csv")
data9 <- read.csv("data/The Hollywood Inider - all data - 2015.csv")
data10 <- read.csv("data/The Hollywood Inider - all data - 2016.csv")
data11 <- read.csv("data/The Hollywood Inider - all data - 2017.csv")
data12 <- read.csv("data/The Hollywood Inider - all data - 2018.csv")
data13 <- read.csv("data/The Hollywood Inider - all data - 2019.csv")
data14 <- read.csv("data/The Hollywood Inider - all data - 2020.csv")
data15 <- read.csv("data/The Hollywood Inider - all data - 2021.csv")
data16 <- read.csv("data/The Hollywood Inider - all data - 2022.csv")
```

The data source that I chose for my project is called [Hollywood Hits and Flops (2007 - 2023)](https://www.kaggle.com/datasets/sujaykapadnis/hollywood-hits-and-flops-2007-2023/) found on [Kaggle](https://www.kaggle.com). This contains numerous details pertaining to the success rate of hundreds of movies from 2007-2023, such as the Rotten Tomatoes score, audience size, genre, opening weekend revenue, oscar wins, etc. All of the movies range in popularity and success rate, and there are numerous genres and script types represented. There are 16 different csv files as each corresponds to a year from 2007-2023, so joining datasets is necessary. However, the data sets for 2007-2010 have 33 variables, 2011-2018 have 34 variables, and 2019-2022 have 35 variables, so I will have to do some work to ensure that all the data sets have the same number of variables. Additionally, there are some slight differentiations in column names between some data sets, so that will need some cleaning before I combine everything into one single data set.

## Why this data

As an avid movie enthusiast, I chose this dataset because I think it would be very interesting to analyze and compare how various factors can contribute to a movie's success or flop rate. With over 30 variables in the data set, this presents the opportunity to make a wide range of complex multivariate analyses to better understand my data and bring about insights that I may not have considered before regarding movies and their success. Some questions of interest that I have for my analysis include discovering what the most/least popular movie genres are and how that compares across the years 2007-2023, how the critic ratings relate to revenue, how the audience numbers relate to Oscar wins, and more. I am also interested in devising a formula to calculate concrete numbers for the success rate of each movie based on a combination of the variables included.

## Data quality & complexity check

As stated previously, there are 16 separate data sets for each of the years between 2007 and 2023. The data sets for 2007-2010 have 33 variables, 2011-2018 have 34 variables, and 2019-2022 have 35 variables, and the number of observations ranges from 66-160. After combining all of the separate data sets into one, there should be about 2,000 observations and 33 variables (I will remove the extra variables for the years where there are more than 33 variables). There are 12 categorical and 21 numerical variables. For all of the data sets, there appears to be NAs in all of the observations for the variables "financial source, if not the numbers" and "film list here...", so those variables are most likely going to be removed. Additionally, there is a column called "None" with NAs for everything observation, and that is most likely going to be removed as well as I am not sure what the purpose of that variable is. Finally, some years do not have information for "distributor", "IMDb rating", and "IMDb vs RT disparity", while others do have that information present.

## Potential data issues

When joining my data sets, it is not going to be a simple and straightforward combining-- the data sets have different numbers of variables from 33-35, so I will have to do some cleaning to ensure that all the data sets have the same number of variables. Additionally, there are some minute differences in column names between some data sets (eg. "Genre" vs. "Genres"), so I will also need to clean the names and rename so that all the data sets have the same variable names before combining. Finally, variables where percentages are included are classified as character variables, so I may need to drop the percent signs from these observations and convert those values into numerical types in order to be able to make calculations and analyses.

## Misc

I plan to use line graphs and density plots to visualize data comparisons and changes over time over the course of 2007-2023, and visualizations within each specific year will be represented by other graph types such as bar graphs to show the distribution of genres for that year (or facet by year). I also will make use of summary statistics and correlations to calculate significant values regarding success rate.

## References

Kaggle (2023). Hollywood Hits and Flops data set <https://www.kaggle.com/datasets/sujaykapadnis/hollywood-hits-and-flops-2007-2023>
